### ISSUE TITLE
Add ruby linting

### ISSUE THREAD

**Issue by kntsoriano** [nkpgardose/Administrivia#6]
Since we have js and css hint installed, I suggest that we also add linting for ruby. We could use the [rubocop](https://github.com/bbatsov/rubocop) gem. It comes with very strict defaults though, so maybe we need to discuss which rules `rubocop` would be enforcing.

**Comment by nkpgardose** [comment]
Added rubocop to the Gemfile. https://github.com/nkpgardose/Administrivia/commit/b8ec87063083a37959f2ecc879c9b766a6883b3d
Running rubocop on the project result to
<img width="387" alt="screen shot 2015-12-12 at 10 57 09 am" src="https://cloud.githubusercontent.com/assets/3381818/11759809/21a35c74-a0bf-11e5-8e97-93d5e2cbb0af.png">
and I agree that we need to modify its default rules.
